---
- hosts: all
  become: true
  tasks:
    
    - name: Installing traceroute and curl packages on hosts
      apt:
        name:
          - traceroute
          - curl
        update_cache: yes
        state: present
      ignore_errors: true

    - name: Installing knockd package on centralServer and inetRouter    
      apt:
        name: knockd
        state: present
      ignore_errors: true
      when: ansible_hostname == "centralServer" or ansible_hostname == "inetRouter"

    - name: Installing NGINX on centralServer
      apt:
        name: nginx
        state: present
      ignore_errors: true
      when: ansible_hostname == "centralServer"

    - name: Set up forward packages across routers
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
      when: "'routers' in group_names"

    - name: Disabling default route on all hosts except inetRouter and inetRouter2
      template:
        src: 50-cloud-init.j2
        dest: /etc/netplan/50-cloud-init.yaml
        owner: root
        group: root
        mode: 0644
      when:
        - ansible_hostname != "inetRouter" 
        - ansible_hostname != "inetRouter2"   

    - name: Route configuring on hosts
      template:
        src: 50-vagrant-{{ ansible_hostname }}.j2
        dest: /etc/netplan/50-vagrant.yaml
        owner: root
        group: root
        mode: 0644


- name: Configuring inetRouter
  hosts: inetRouter
  become: true
  tasks:
    - name: Disabling ufw service
      systemd:
        name: ufw
        state: stopped
        enabled: no

    - name: Installing iptables-persistent service
      apt:
        name: iptables-persistent
        state: present
      ignore_errors: true 
    
    - name: Set up NAT
      template:
        src: rules_inetRouter.v4
        dest: /etc/iptables/rules.v4
        owner: root
        group: root
        mode: 0644

    - name: Configuring SSH service
      replace:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        regexp: "PasswordAuthentication no"
        replace: "PasswordAuthentication yes"
    
    - name: Restarting SSH service
      systemd:
        name: sshd
        state: restarted

    - name: Turn on cnockd
      template:
        src: knockd.j2
        dest: /etc/default/knockd
        owner: root
        group: root
        mode: 0644

    - name: Make /etc/systemd/system/knockd.service
      template:
        src: knockd.service.j2
        dest: /etc/systemd/system/knockd.service
        owner: root
        group: root
        mode: 0755

    - name: Change config /etc/knockd.conf
      template:
        src: knockd.conf.j2
        dest: /etc/knockd.conf
        owner: root
        group: root
        mode: 0644 

    - name: Start knockd service
      systemd:
        name: knockd
        state: started
        enabled: yes           
       
- name: Configuring inetRouter2
  hosts: inetRouter2
  become: true
  tasks:
    - name: Disabling ufw service
      systemd:
        name: ufw
        state: stopped
        enabled: no

    - name: Installing iptables-persistent service
      apt:
        name: iptables-persistent
        state: present
      ignore_errors: true 
    
    - name: Set up NAT
      template:
        src: rules_inetRouter2.v4
        dest: /etc/iptables/rules.v4
        owner: root
        group: root
        mode: 0644 

...